on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
      - name: Run Script with Secrets
        env:
          USERNAME_TO_CHECK: ${{ secrets.USERNAME_TO_CHECK }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: node scraper.js
